### ISSUE TITLE
Issue : oceanctl command

### ISSUE THREAD

**Issue by ccaillet1974** [Huawei/eSDK_K8S_Plugin#132]
Hi all,

Environement :
* k8s : v1.24.6 deployed with kubespray
* OS for nodes : debian 11.x
* CNI : cilium 1.12.4

I've the following issue when try to create a backend : 

```
bin/oceanctl create backend -n kube-storage -f backend-oc5k-nfs.yaml
Error: output: ; error: error: the server doesn't have a resource type "storagebackendclaim"
```

I join the backend content of the backend YAML file : 

```
storage: "oceanstor-nas"
name: "oc5k-nfs"
namespace: "kube-storage"
urls:
- "https://10.211.64.132:8088"
pools:
- "FS_Pool"
parameters:
  protocol: "nfs"
  portals:
  - "10.144.68.192"
maxClientThreads: "30"
```

Could you assist me for troubleshoot ?

Regards,
Christophe
