### ISSUE TITLE
pvc create by system user account backend attach Volume failed: Internal desc = Add lun 29 to group 1 error: 1073807373

### ISSUE THREAD

**Issue by fangfenghuang** [Huawei/eSDK_K8S_Plugin#143]
- v4.2.1
- backend:

```yaml
---
storage: "oceanstor-san"
name: "oceanstor-iscsi-sysuser01"
namespace: "huawei-csi"
urls:
 - "https://192.168.55.X:8088"    # 存储设备的管理URL。
pools:
 - "StoragePool001"                    # 存储设备的存储池。
parameters:
 protocol: "iscsi"                         # 存储协议：iscsi、fc、roce、fc-nvme、nfs、dpc、scsi
 portals:
 - "10.10.4.X"                              # 业务访问端口
maxClientThreads: "30"             # 默认最大连接数为30
```
- sc:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oceanstor-sysuser01-noqos
parameters:
  allocType: thin
  backend: oceanstor-iscsi-sysuser01
  fsType: xfs
  volumeType: lun
provisioner: csi.huawei.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

- pod logs:
```yaml
  Normal   Scheduled           8m7s                  default-scheduler        Successfully assigned default/hff-sts-pvc-0 to telecom-k8s-virt4
  Warning  FailedAttachVolume  108s (x11 over 8m6s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-92b9c757-560e-4842-89d0-c5b1635f8039" : rpc error: code = Internal desc = Add lun 29 to group 1 error: 1073807373
  Warning  FailedMount         91s (x3 over 6m4s)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[hff-sts-pvc], unattached volumes=[hff-sts-pvc kube-api-access-kvnwt]: timed out waiting for the condition
```
I tried using the admin user and it didn't work, but the vStore user works well. 
And pvc status is Bound, resizing ok.
```bash
Events:
  Type     Reason                  Age    From                                                                   Message
  ----     ------                  ----   ----                                                                   -------
  Normal   Provisioning            7m11s  csi.huawei.com_telecom-k8s-virt3_e1f5aebe-ebb8-4cf8-870b-d548c87a3580  External provisioner is provisioning volume for claim "default/hff-sts-pvc-hff-sts-pvc-0"
  Normal   ExternalProvisioning    7m11s  persistentvolume-controller                                            waiting for a volume to be created, either by external provisioner "csi.huawei.com" or manually created by system administrator
  Normal   ProvisioningSucceeded   7m10s  csi.huawei.com_telecom-k8s-virt3_e1f5aebe-ebb8-4cf8-870b-d548c87a3580  Successfully provisioned volume pvc-5d166e42-8f3e-4d3f-84c9-922e91659243
  Warning  ExternalExpanding       34s    volume_expand                                                          Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                34s    external-resizer csi.huawei.com                                        External resizer is resizing volume pvc-5d166e42-8f3e-4d3f-84c9-922e91659243
  Normal   VolumeResizeSuccessful  34s    external-resizer csi.huawei.com                                        Resize volume succeeded
```
