### ISSUE TITLE
Can't mount multiple pvc in one pod with fsGroup setting

### ISSUE THREAD

**Issue by pbabilas** [Huawei/eSDK_K8S_Plugin#68]
When I'm trying to mount multiple pvc into one pod, only first mount gets fsgroup settings set correct.
But problem is only when mount 2 or more huwawei pv mixing other storageclasses works fine.

**Comment by pbabilas** [comment]
It seams its new version problem.

the same configuration on v2.2.13:
```drwxr-xr-x 1 root root      30 Jun 22 12:33 .
drwxr-xr-x 1 root root      61 Jun 22 12:33 ..
drwxrwsrwx 2 root mongodb    6 Jun 22 12:32 empty
drwxrwsr-x 3 root mongodb 4.0K Jun 22 12:32 old
```
and v2.2.16:
```
mongodb@mongo:/mnt$ ls -lah
total 4.0K
drwxr-xr-x 1 root root      30 Jun 22 11:59 .
drwxr-xr-x 1 root root      61 Jun 22 11:59 ..
drwxrwsrwx 2 root mongodb    6 Jun 22 11:58 empty
drwxr-xr-x 2 root root    4.0K Jun 22 11:41 old
```

:(

**Comment by pbabilas** [comment]
Ok, I've found resolution. Just apply CSI Driver:

```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.huawei.com
spec:
  fsGroupPolicy: File
```
And mounting works fine.
